# Generated by Django 3.1.5 on 2021-05-11 13:54

import CVgallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVgallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccountPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_image', models.ImageField(upload_to=CVgallery.models.social_media_upload_path)),
            ],
        ),
    ]
