# Generated by Django 3.1.5 on 2021-03-28 21:23

import CVprojects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LANGUAGE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('caption', models.TextField(max_length=700)),
                ('slug', models.SlugField(blank=True, max_length=20, unique=True)),
                ('source_code', models.CharField(blank=True, max_length=200)),
                ('imagMain', models.ImageField(upload_to=CVprojects.models.media_upload_path)),
                ('imageSub1', models.ImageField(blank=True, upload_to=CVprojects.models.media_upload_path)),
                ('imageSub2', models.ImageField(blank=True, upload_to=CVprojects.models.media_upload_path)),
                ('imageSub3', models.ImageField(blank=True, upload_to=CVprojects.models.media_upload_path)),
                ('views', models.PositiveIntegerField(default=0)),
                ('isActive', models.BooleanField(default=True)),
                ('technology', models.ManyToManyField(blank=True, to='CVprojects.LANGUAGE')),
            ],
        ),
    ]
