# Generated by Django 3.1.5 on 2021-04-03 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVprojects', '0003_auto_20210330_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=40),
        ),
    ]
