# Generated by Django 3.1.5 on 2021-06-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVprojects', '0006_project_previwlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_features',
            field=models.TextField(blank=True, max_length=700),
        ),
    ]
