# Generated by Django 3.1.5 on 2021-03-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVhome', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='grey',
            field=models.TextField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='home',
            name='p1',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='home',
            name='p2',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.TextField(blank=True, max_length=80),
        ),
    ]
