# Generated by Django 3.1.5 on 2021-04-23 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVhome', '0003_auto_20210409_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='bigImg',
        ),
        migrations.RemoveField(
            model_name='home',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='home',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='home',
            name='slang',
        ),
    ]
