# Generated by Django 3.1.5 on 2021-04-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVhome', '0004_auto_20210423_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='github',
        ),
        migrations.RemoveField(
            model_name='home',
            name='insta',
        ),
        migrations.RemoveField(
            model_name='home',
            name='linkedin',
        ),
    ]
