# Generated by Django 3.1.5 on 2021-05-11 13:36

import CVhome.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVhome', '0005_auto_20210423_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccountPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_image', models.ImageField(upload_to='/')),
            ],
        ),
    ]
