# Generated by Django 3.1.5 on 2021-05-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVhome', '0006_sitesetting_socialaccountposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='instagram',
            new_name='is_instagram_feed_active',
        ),
    ]
