# Generated by Django 3.1.5 on 2021-05-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CVhome', '0007_auto_20210511_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialAccountPosts',
        ),
    ]
